name: Set Issue Label and Assignee
'on':
  issues:
    types:
      - opened
  pull_request:
    typed:
      - opened
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: Naturalclar/issue-action@v2.0.2
        with:
          title-or-body: both
          parameters: >-
            [ {"keywords": ["backend", "database", "db"], "assignees":
            ["Hougesen"], "labels": ["backend"]}, {"keywords": ["frontend"], "assignees": ["Hougesen",
            "Abdjulaziz"],"labels": ["frontend"]}, {"keywords": ["design"], "assignees":
            ["khalidalatti", "Hougesen", "Abdjulaziz",
            "skrog19"],"labels": ["design"]},{"keywords":["fix", "bug", "fejl", "error"],
            "assignees": ["Hougesen", "Abdjulaziz"] ,"labels": ["BUG"]}]
          github-token: '${{ secrets.GITHUB_TOKEN }}'
